Import modified configure.in from YTalk 3.1.2
git-svn-id: file:///Users/kling/src/protoman/svn/trunk/ytalk@10 8120b729-f3fe-0310-9465-b9035d29392c

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -1,13 +1,18 @@
-dnl configure.in for Ytalk; started 14NOV98 by Roger Espel Llima
+dnl configure.in for YTalk
 dnl Process this file with autoconf to produce a configure script.
 
-AC_INIT(comm.c)
+AC_INIT(YTalk, 3.2.0)
+AC_REVISION($LastChangedRevision: 77 $)
 AC_CONFIG_HEADER(config.h)
 
 dnl Checks for programs.
 AC_PROG_CC
 AC_PROG_CPP
 AC_PROG_INSTALL
+AC_PROG_MAKE_SET
+
+dnl Sanity
+AC_CHECK_SIZEOF(long)
 
 dnl Checks for libraries.
 AC_CHECK_LIB(ncurses, initscr,, no_ncurses=1)
@@ -36,44 +41,54 @@ if test "x$no_termios" = "x1" ; then
   AC_CHECK_HEADERS(sgtty.h,, AC_MSG_ERROR(Cannot find either termios or sgtty))
 fi
 
-dnl Check for X's stuff
-AC_PATH_XTRA
-if test "x$no_x" != "xyes" ; then
-  XLIBS="$X_PRE_LIBS $X_LIBS -lX11 $X_EXTRA_LIBS"
-else
+dnl X setup.
+AC_ARG_WITH(x, 
+  AC_HELP_STRING([--with-x], [use the X Window System]),
+  no_x=0, no_x=1)
+if test "x$no_x" = "x1"; then
+  AC_DEFINE([X_DISPLAY_MISSING])
   XLIBS=""
+  XINCS=""
+else
+  AC_PATH_XTRA
+  if test "x$X_LIBS" = "x"; then
+    echo "No X found but --with-x stated, aborting!"
+    exit 1
+  fi
+  XLIBS="$X_PRE_LIBS $X_LIBS -lX11 $X_EXTRA_LIBS"
+  XINCS="$X_CFLAGS"
+  AC_LIBOBJ([xwin])
 fi
-XINCS="$X_CFLAGS"
 AC_SUBST(XLIBS)
 AC_SUBST(XINCS)
 
-dnl Some systems need extra libraries for sockets and dns ...
+dnl Some systems need extra libraries for sockets and dns...
 AC_CHECK_FUNC(socket,,AC_CHECK_LIB(socket, socket,, [AC_MSG_ERROR(Can't compile without socket)]))
 AC_CHECK_FUNC(gethostbyname,,AC_CHECK_LIB(nsl, gethostbyname,, [AC_MSG_ERROR(Can't compile without gethostbyname)]))
 
 dnl Checks for header files.
-AC_CHECK_HEADERS(fcntl.h sys/ioctl.h sys/time.h stropts.h unistd.h)
-AC_CHECK_HEADERS(iovec.h sys/uio.h)
-dnl AC_CHECK_HEADERS(termios.h sgtty.h, break)
-
-dnl if test "x$ac_cv_header_termios_h" != "xyes" -a "x$ac_cv_header_sgtty_h" != "xyes" ; then
-dnl   AC_MSG_ERROR(Cannot find either termios or sgtty)
-dnl fi
+AC_PATH_X
+AC_HEADER_STDC
+AC_HEADER_SYS_WAIT
+AC_CHECK_HEADERS(fcntl.h netdb.h netinet/in.h sys/ioctl.h sys/time.h unistd.h stropts.h)
+AC_CHECK_HEADERS(iovec.h sys/uio.h stdlib.h string.h sys/param.h arpa/inet.h)
 
 dnl Checks for typedefs, structures, and compiler characteristics.
-AC_HEADER_TIME
-
-AC_TYPE_SIGNAL
 AC_TYPE_SIZE_T
-
-AC_CHECK_FUNC(gethostname,,AC_MSG_ERROR(Can't run without gethostname))
-AC_CHECK_FUNC(select,,AC_MSG_ERROR(Can't compile without select))
+AC_TYPE_SIGNAL
+AC_HEADER_TIME
+AC_TYPE_UID_T
 
 dnl Checks for library functions.
 AC_PROG_GCC_TRADITIONAL
 AC_CHECK_FUNCS(putenv strerror ttyname ptsname grantpt unlockpt)
-AC_CHECK_FUNCS(setsid tcflush)
+AC_CHECK_FUNCS(setsid tcflush strcpy)
 AC_CHECK_FUNCS(sigprocmask sigsetmask sighold, break)
+AC_CHECK_FUNCS(dup2 endpwent inet_ntoa memset strchr)
 
-AC_OUTPUT(Makefile)
+AC_CHECK_FUNC(gethostname,,AC_MSG_ERROR(Can't run without gethostname))
+AC_CHECK_FUNC(select,,AC_MSG_ERROR(Can't compile without select))
 
+AC_CONFIG_FILES(Makefile)
+
+AC_OUTPUT
